### ISSUE TITLE
Gas Optimization #2: Use `external` instead of `public`

### ISSUE THREAD

**Issue by IntelMin** [Datagen-Project/DataGen-Smart-Contracts#10]
`external` functions are cheaper than `public` functions.
https://ethereum.stackexchange.com/questions/19380/external-vs-public-best-practices

When a function has no calls inside its smart contract, we can use `external` instead of `public`.
Here are those functions which could be updated to `external`.

- MiningReservation.sol
`releaseDataGen`, 

- ReservedPool.sol
`releaseDataGen`, `setCompanyWallet`

- RetailPrivateSale.sol
`checkFunds`, `checkDataGenFunds`, `claimDataGen`, `withdrawUSDC`, `withdrawDataGen`

- TeamBonusPool.sol
`checkBouns`, `checkBalance`

- TeamMainPool.sol
`checkSalary`, `checkBalance`

- VCPrivateSale.sol
`checkFunds`, `checkDataGenFunds`, `claimDataGen`, `withdrawUSDC`, `withdrawDataGen`

**Comment by viac92** [comment]
Change to external in the RetailPrivateSale.sol and VCPrivateSale.sol
