### ISSUE TITLE
Gas Optimization #3: Remove unnecessary variables and functions

### ISSUE THREAD

**Issue by IntelMin** [Datagen-Project/DataGen-Smart-Contracts#11]
Following variables and functions are unnecessary and could be removed.

- CoFounderPool.sol
`checkFunds()`

- ReservedPool.sol
`checkFunds()`

- RetailPrivateSale.sol
`getETHBalance()`

- TeamBonusPool.sol
`isBonusReceiver`

- TeamMainPool.sol
`isSalaryReceiver`

- VCPrivateSale.sol
`getETHBalance()`

We have alternative ways to get ETH and Token balances of a certain address. So we don't need to make additional functions like `checkFunds()` and `getETHBalance()`.
In the current code, `isBonusReceiver` and `isSalaryReceiver` mappings are used to check if `msg.sender` is valid address for receiving bonus or salary. Instead of those variables, we can use existing `bonus` and `mainSalary` mappings.

**Comment by viac92** [comment]
Removed unnecessary functions in RetailPrivateSale.sol and VCPrivateSale.sol
