### ISSUE TITLE
Remove dangerous functions

### ISSUE THREAD

**Issue by IntelMin** [Datagen-Project/DataGen-Smart-Contracts#12]
Following functions are dangerous since anyone can change the important variables.

- CoFounderPool.sol
`setReleaseTime()`

- VCPrivateSale.sol
`setLockTime()`

**Comment by viac92** [comment]
Removed `setLockTime` in the VCPrivateSale.sol.

I think is better to define functions for testing like `functionTest()` and remove it when push on the main branch.

**Comment by viac92** [comment]
Removed all the test functions.
