### ISSUE TITLE
Code issues in MiningReservation.sol

### ISSUE THREAD

**Issue by IntelMin** [Datagen-Project/DataGen-Smart-Contracts#13]
[MiningReservation.sol](https://github.com/Datagen-Project/DataGen-Smart-Contracts/blob/main/contracts/MiningReservation.sol)

- [Line#48](https://github.com/Datagen-Project/DataGen-Smart-Contracts/blob/main/contracts/MiningReservation.sol#L48)
This line should be changed into `epochs = epochs - 1095`.
Because, the original code `epochs = 1` , only works if we call this function `releaseDataGen()` every day after lock time.
We should think unexpected situations in the future.

- [Line#61](https://github.com/Datagen-Project/DataGen-Smart-Contracts/blob/main/contracts/MiningReservation.sol#L61)
This line should be changed into `releaseAmount = beginAmount.mul(epochs).add(releaseAmount);`.
The original code ignores the previous value of `releaseAmount`.

**Comment by fantasy2345** [comment]
Fixed two bugs.
