### ISSUE TITLE
CoFounderPool.sol setaWallet,setlWallet function could be dangerous if don't use with modifier

### ISSUE THREAD

**Issue by fantasy2345** [Datagen-Project/DataGen-Smart-Contracts#6]
We have to use modifier for both of functions like this.
  /* modifier for only Angela,Luca can call setaWallet,setlWallet function */
  modifier onlyAngela( address _angela) {
    require( aWallet == _angela,"You are not the wallet owner.");
    _;
  }

  modifier onlyLuca( address _luca) {
    require( lWallet == _luca,"You are not the wallet owner.");
    _;
  }

  /* aWallet update, only Angela can do. */
  function setaWallet(address _aWallet) external onlyAngela(msg.sender) {
    aWallet = _aWallet;
    emit SetaWalletAddress(msg.sender, _aWallet);
  }

  /* lWallet update, only Luca can do. */
  function setlWallet(address _lWallet) external onlyLuca(msg.sender) {
    lWallet = _lWallet;
    emit SetlWalletAddress(msg.sender, _lWallet);
  }

**Comment by Lord-Nymphis** [comment]
Ok, but if your suggestion were to be approved, you would directly push the code as 
we find in the issue above?
