### ISSUE TITLE
Gas Optimization #1: Use constant variables if possible

### ISSUE THREAD

**Issue by IntelMin** [Datagen-Project/DataGen-Smart-Contracts#9]
Constant variables use less gas than normal variables.
Also, using constants is much effective for security.

We can define these variables as constant.

- CoFounderPool.sol
`cfAmount`, `rcfAmount`, `beginAmount`

- MiningReservation.sol
`lockTime`, `totalLocked`, `startAmount`

- ReservedPool.sol
`frAmount`, `frStart`, `srAmount`, `srStart`

- RetailPrivateSale.sol
`maxGoal`, `discountLimit`, `USDC_ADDRESS`

- TeamBonusPool.sol
`totalAmount`, `lockTime`, `deadAddress`

- TeamMainPool.sol
`totalAmount`, `lockTime1`, `lockTime2`, `lockTime3`, `deadAddress`

- VCPrivateSale.sol
`maxGoal`, `USDC_ADDRESS`

**Comment by viac92** [comment]
Define contants for `maxGoal`, `discountLimit` in RetailprivateSale.sol and for `maxGoal` in VCPrivateSale.sol.
Left the USDC_ADDRESS as a variable in the constructor for testing.
